language: c
compiler:
  - gcc
  - clang
dist: xenial

addons:
  apt:
    packages:
      - libcmocka-dev
      - libcmocka0
      - gnulib
      - gnu-efi

env:
  global:
    - JOBS="$(($(nproc)*3/2))"
    - PREFIX=/usr
    - MAKE="make --jobs=$JOBS"

after_failure:
  - cat tpm2-tcti-uefi-*/_build/sub/test-suite.log

install:
  - wget https://download.01.org/tpm2/autoconf-archive-2017.09.28.tar.xz
  - sha256sum autoconf-archive-2017.09.28.tar.xz | grep -q 5c9fb5845b38b28982a3ef12836f76b35f46799ef4a2e46b48e2bd3c6182fa01
  - tar xJf autoconf-archive-2017.09.28.tar.xz && pushd autoconf-archive-2017.09.28
  - ./configure --prefix=${PREFIX}
  - $MAKE
  - sudo $MAKE install
  - popd
  - git clone -b master --single-branch https://github.com/tpm2-software/tpm2-tss.git
  - pushd tpm2-tss
  - ./bootstrap --include=/usr/share/gnulib/m4
  - CONFIG_SITE=../lib/tss2-sys_config.site ./configure --prefix=${PREFIX} --disable-defaultflags --disable-doxygen-doc --disable-tcti-device --disable-tcti-mssim --disable-esapi --with-maxloglevel=none
  - $MAKE
  - sudo $MAKE install
  - popd

before_script:
  - ./bootstrap

script:
  - ./configure --enable-unit
  - $MAKE distcheck
  - $MAKE example
