language: c
python: 2.7
dist: xenial

addons:
  apt:
    packages:
      - expect
      - iasl
      - lcov
      - libcmocka-dev
      - libcmocka0
      - gnulib
      - libglib2.0-dev
      - libpixman-1-dev
      - libssl-dev
      - libtasn1-dev
      - nasm
      - socat
      - uuid-dev

env:
  global:
    - JOBS="$(($(nproc)*3/2))"
    - PREFIX=/usr
    - MAKE="make --jobs=$JOBS"
    - ACLOCAL_DIR="/usr/share/gnulib/m4"
    - TSS2_CONFIG_SITE=${TRAVIS_BUILD_DIR}/.ci/tss2-sys_config.site

matrix:
  include:
    - compiler: clang
      env: SCANBUILD="scan-build --status-bugs" MAKE_TARGET=distcheck
    - compiler: gcc
      env: SCANBUILD= CONFIG_EXTRA="--enable-code-coverage" MAKE_TARGET=check

after_failure:
  - cat tpm2-tcti-uefi-*/_build/sub/test-suite.log

after_success:
  - |
    if [ ! -z "$COVERALLS_REPO_TOKEN" ] && [ "${CC}" = "gcc" ]; then
      coveralls --build-root=$(pwd) --exclude=./example --exclude=./test \
        --gcov-options '\-lp'
    fi

install:
  - pip install --user cpp-coveralls
  - ./.ci/build-deps.sh --prefix=${PREFIX}

before_script:
  - ./bootstrap

script:
  - $SCANBUILD ./configure --enable-unit --enable-integration ${CONFIG_EXTRA}
  - $SCANBUILD $MAKE $MAKE_TARGET
  - $SCANBUILD $MAKE example
