language: c
dist: xenial

addons:
  apt:
    packages:
      - libcmocka-dev
      - libcmocka0
      - gnulib
      - gnu-efi

env:
  global:
    - JOBS="$(($(nproc)*3/2))"
    - PREFIX=/usr
    - MAKE="make --jobs=$JOBS"
    - ACLOCAL_DIR="/usr/share/gnulib/m4"
    - TSS2_CONFIG_SITE=${TRAVIS_BUILD_DIR}/lib/tss2-sys_config.site

matrix:
  include:
    - compiler: clang
      env: SCANBUILD="scan-build --status-bugs"
    - compiler: gcc
      env: SCANBUILD=

after_failure:
  - cat tpm2-tcti-uefi-*/_build/sub/test-suite.log

install:
  - ./.ci/build-deps.sh --prefix=${PREFIX}

before_script:
  - ./bootstrap

script:
  - $SCANBUILD ./configure --enable-unit
  - $SCANBUILD $MAKE distcheck
  - $SCANBUILD $MAKE example
