FROM ubuntu:jammy AS build

ARG PREFIX=/usr

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    autoconf \
    automake \
    bc \
    build-essential \
    cpio \
    iasl \
    expect \
    flex \
    gawk \
    git \
    gnulib \
    lcov \
    libcmocka-dev \
    libglib2.0-dev \
    libpixman-1-dev \
    libssl-dev \
    libtasn1-dev \
    libtool \
    nasm \
    net-tools \
    pkg-config \
    python3 \
    rpm2cpio \
    socat \
    sudo \
    uuid-dev \
    wget

WORKDIR /tmp/build-deps
COPY ./.ci/build-deps.sh ./
COPY ./.ci/tss2-sys_config.site ./
RUN bash -x ./build-deps.sh --prefix=${PREFIX} \
    --tss2-config-site=$(pwd)/tss2-sys_config.site
